baseURL = 'https://nickthien-my.github.io/newagecaveman/'
languageCode = 'en-us'
title = 'New Age Caveman'
theme = 'ananke'

[markup.goldmark.renderer]
unsafe= true

[params]
  text_color = ""
  author = "Nicholas Thien"
  favicon = ""
  site_logo = ""
  description = "Navigating the modern world."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3